In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv(r"C:\Users\abhinandan\Desktop\Machine_learning_full\Online Sales Data.csv")
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
filtered = df[df["Product Category"] == "Home Appliances"]
grouped = filtered.groupby("Product Name")[["Total Revenue", "Units Sold"]].sum()
filtered_grouped = grouped[grouped["Units Sold"] > 20]

top5 = filtered_grouped.sort_values("Total Revenue", ascending=False).head(5)

print(top5)

Empty DataFrame
Columns: [Total Revenue, Units Sold]
Index: []

In [81]:
aaa = df.groupby("Product Category")["Units Sold"].sum()
aaa = aaa.reset_index()

tope = aaa.sort_values("Units Sold", ascending=False).head(5)
print(tope)

  Product Category  Units Sold
2         Clothing         145
1            Books         114
5           Sports          88
3      Electronics          66
4  Home Appliances          59

In [75]:
s = df.groupby(["Region",'Product Name'])["Total Revenue"].sum()
zzzz = s[s>1000]
print(zzzz)

Region         Product Name
Asia           Peloton Bike                         1895.00
Europe         Blueair Classic 480i                 1199.98
               Dyson Supersonic Hair Dryer          1199.97
               LG OLED TV                           2599.98
               Roomba i7+                           1599.98
North America  Apple MacBook Air                    1199.99
               Apple MacBook Pro 16-inch            2399.00
               Apple Watch Series 8                 1199.97
               Apple iPad Air                       1199.98
               Canon EOS R5 Camera                  3899.99
               GoPro HERO10 Black                   1199.97
               HP Spectre x360 Laptop               1599.99
               MacBook Pro 16-inch                  2499.99
               Microsoft Surface Laptop 4           1299.99
               Samsung Galaxy Tab S8                1499.98
               Samsung Odyssey G9 Gaming Monitor    1499.99
               Samsung QLED 4K TV                   1199.99
               Sony WH-1000XM4 Headphones           1049.97
               iPhone 14 Pro                        1999.98
Name: Total Revenue, dtype: float64

In [74]:
az = df[df["Product Category"]=="Clothing"].groupby("Product Name")['Total Revenue'].sum()
az = az.reset_index()

topp = az.sort_values("Total Revenue",ascending=(False)).head(3) 
print(topp)

                  Product Name  Total Revenue
22            Nike Air Force 1         539.94
27      North Face Down Jacket         499.98
32  Ray-Ban Aviator Sunglasses         464.97

In [61]:
df.groupby(["Region","Product Category"])["Total Revenue"].sum()

Region         Product Category
Asia           Clothing             8128.93
               Sports              14326.52
Europe         Beauty Products      2621.90
               Home Appliances     18646.16
North America  Books                1861.93
               Electronics         34982.41
Name: Total Revenue, dtype: float64

In [60]:
aqwe = df[df["Product Category"] == "Books"].groupby("Region")["Units Sold"].sum()
kar = aqwe.idxmax()
aka = aqwe.max()
print(kar,aka)

North America 114

In [55]:
aqqqe = df.groupby("Payment Method")["Total Revenue"].sum()
hssj = aqqqe.idxmax()
dhdh = aqqqe.max()
print(hssj,dhdh)

Credit Card 51170.86

In [ ]:
abc = df[df["Product Category"] == "Beauty Products"].groupby("Product Name")["Total Revenue"].sum()
aee = abc.idxmax()
ade = abc.max()

print(aee,ade)

Dyson Supersonic Hair Dryer 399.99

In [63]:
ab = df.groupby(["Region", "Product Category"])["Total Revenue"].sum()
ab = ab.reset_index()  

top = ab.sort_values(["Region", "Total Revenue"], ascending=[True, False]).drop_duplicates("Region")
print(top)

          Region Product Category  Total Revenue
1           Asia           Sports       14326.52
3         Europe  Home Appliances       18646.16
5  North America      Electronics       34982.41

In [33]:
df.groupby(["Product Name","Region"]) ["Unit Price"].sum()

Product Name                                        Region
1984 by George Orwell                               North America     19.99
Adidas 3-Stripes Shorts                             Asia              29.99
Adidas Essential Track Pants                        Asia              44.99
Adidas FIFA World Cup Football                      Asia              29.99
Adidas Originals Superstar Sneakers                 Asia              79.99
                                                                      ...
Yeti Tundra Haul Portable Wheeled Cooler            Asia             399.99
Youth to the People Superfood Antioxidant Cleanser  Europe            36.00
Zara Summer Dress                                   Asia              59.99
iPhone 14 Pro                                       North America    999.99
iRobot Braava Jet M6                                Europe           449.99
Name: Unit Price, Length: 233, dtype: float64

In [8]:
df.groupby('Product Name').agg({
    'Units Sold': 'sum',
    'Total Revenue' :'sum'
    })

                                                    Units Sold  Total Revenue
Product Name
1984 by George Orwell                                        4          79.96
Adidas 3-Stripes Shorts                                      5         149.95
Adidas Essential Track Pants                                 3         134.97
Adidas FIFA World Cup Football                               3          89.97
Adidas Originals Superstar Sneakers                          4         319.96
...                                                        ...            ...
Yeti Tundra Haul Portable Wheeled Cooler                     1         399.99
Youth to the People Superfood Antioxidant Cleanser           1          36.00
Zara Summer Dress                                            3         179.97
iPhone 14 Pro                                                2        1999.98
iRobot Braava Jet M6                                         1         449.99

[232 rows x 2 columns]

In [9]:
x = df.groupby('Product Name')[["Units Sold",'Total Revenue']].sum()
x

                                                    Units Sold  Total Revenue
Product Name
1984 by George Orwell                                        4          79.96
Adidas 3-Stripes Shorts                                      5         149.95
Adidas Essential Track Pants                                 3         134.97
Adidas FIFA World Cup Football                               3          89.97
Adidas Originals Superstar Sneakers                          4         319.96
...                                                        ...            ...
Yeti Tundra Haul Portable Wheeled Cooler                     1         399.99
Youth to the People Superfood Antioxidant Cleanser           1          36.00
Zara Summer Dress                                            3         179.97
iPhone 14 Pro                                                2        1999.98
iRobot Braava Jet M6                                         1         449.99

[232 rows x 2 columns]

In [10]:
x = df.groupby('Region')['Units Sold'].sum()
top = x.idxmax()
val = x.max()
print(top , val)

Asia 233

In [11]:
a = df.groupby('Region')['Total Revenue'].sum()
a

Region
Asia             22455.45
Europe           21268.06
North America    36844.34
Name: Total Revenue, dtype: float64

In [12]:
b = df.groupby('Product Category')['Units Sold'].sum()
b

Product Category
Beauty Products     46
Books              114
Clothing           145
Electronics         66
Home Appliances     59
Sports              88
Name: Units Sold, dtype: int64

In [13]:
c = df.groupby('Product Name')['Total Revenue'].sum()
top_product = c.idxmax()  
top_value = c.max()       

print(top_product, top_value)

Canon EOS R5 Camera 3899.99

In [14]:
d = df.groupby('Payment Method')['Total Revenue'].sum()
d

Payment Method
Credit Card    51170.86
Debit Card      8128.93
PayPal         21268.06
Name: Total Revenue, dtype: float64

In [15]:
df[df["Region"]=='North America'].groupby('Product Name')["Total Revenue"].sum()

Product Name
1984 by George Orwell                       79.96
Amazon Echo Dot (4th Gen)                  199.96
Amazon Echo Show 10                        249.99
Amazon Fire TV Stick 4K                    149.97
Anker PowerCore Portable Charger           239.96
                                           ...
The Sun Also Rises by Ernest Hemingway      35.97
Think and Grow Rich by Napoleon Hill        29.97
To Kill a Mockingbird by Harper Lee         59.96
Where the Crawdads Sing by Delia Owens      75.96
iPhone 14 Pro                             1999.98
Name: Total Revenue, Length: 75, dtype: float64

In [16]:
df[df["Payment Method"]=="Credit Card"].groupby('Product Category')['Unit Price'].mean()

Product Category
Books           16.1530
Electronics    691.5915
Sports         261.2840
Name: Unit Price, dtype: float64

In [17]:
top_products = (
    df.groupby(['Product Category', 'Product Name'])['Total Revenue'].sum()
    .reset_index()
    .sort_values(['Product Category', 'Total Revenue'], ascending=[True, False])
    .drop_duplicates('Product Category')
)

print(top_products)

    Product Category                            Product Name  Total Revenue
10   Beauty Products             Dyson Supersonic Hair Dryer         399.99
70             Books  The Silent Patient by Alex Michaelides         134.95
98          Clothing                        Nike Air Force 1         539.94
130      Electronics                     Canon EOS R5 Camera        3899.99
182  Home Appliances                              LG OLED TV        2599.98
217           Sports                            Peloton Bike        1895.00

In [18]:
y = df[df["Payment Method"]=='PayPal'].groupby('Product Name')['Total Revenue'].sum()
z = y[y>1000]
print(z)

Product Name
Blueair Classic 480i           1199.98
Dyson Supersonic Hair Dryer    1199.97
LG OLED TV                     2599.98
Roomba i7+                     1599.98
Name: Total Revenue, dtype: float64